name: flat_buffers
version: 23.5.26
description: FlatBuffers reading and writing library for Dart. Based on original work by Konstantin Scheglov and Paul Berry of the Dart SDK team.
homepage: https://github.com/google/flatbuffers
documentation: https://google.github.io/flatbuffers/index.html

environment:
  sdk: '3.2.3'

dev_dependencies:
  test: 1.24.9
  test_reflective_loader: 0.2.2
  path: 1.9.0
  lints: 1.0.1
